//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices()
        {
            this.DeviceProperties = new HashSet<DeviceProperties>();
        }
    
        public int Id { get; set; }
        public string FullLabel { get; set; }
        public string FullName2 { get; set; }
        public int Hidden { get; set; }
        public int Label { get; set; }
        public int Localization { get; set; }
        public int LogicalChildren { get; set; }
        public int LogicalParent { get; set; }
        public int Name { get; set; }
        public int PhisicalChildren { get; set; }
        public int PhisicalParent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceProperties> DeviceProperties { get; set; }
    }
}
