//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenants
    {
        public int Id { get; set; }
        public int Name { get; set; }
        public int Permissions { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
    
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
