spring:
profiles:
   active: default
   datasource:
          driverClassName: org.h2.Driver
          url: jdbc:h2:tcp://localdhost/~/hr1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: hr1
          password: hr1
   jpa:
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true
   h2:
    console:
      enabled: true
      path: /h2-console