spring:
  datasource:
          driverClassName: org.h2.Driver
          url: jdbc:h2:tcp://localhost/~/msaw5;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: msaw5
          password: msaw5
  profiles:
     active: default
  jpa:
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
      path: /h2-console
  server:
  error:
  whitelabel:
  enabled: false