spring:
  datasource:
          driverClassName: org.h2.Driver
          url: jdbc:h2:tcp://localhost/~/msaw5
          username: msaw5
          password: msaw5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
      path: /h2-console